# Generated by Django 4.2.2 on 2023-06-11 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_remove_image_image_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
